language: java
before_script:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
script:  "sudo mvn -f ./app/pom.xml -Dandroid.sdk.path=./android-sdk-linux clean install"
