language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=~/builds/leviwilson/oasis-android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2,4,9 --no-ui --force
  - android update project --path ./app
  - android update project --path ./integration
  - echo no | android create avd -n android-10 -t 1
  - emulator -avd android-10 -no-window &
after_install:
  - killall emulator-arm
