language: java
before_script:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - chmod -R 777 ./android-sdk-linux
  - export ANDROID_HOME=./android-sdk-linux
script:  "sudo mvn -f ./app/pom.xml clean install"
