language: java
before_script:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxvf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=./android-sdk-linux
script:  "mvn -f ./app/pom.xml clean install"
