language: java
jdk:
  - openjdk6
before_install:
  - gem install calabash-android
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export CALABASH_APP_BASE=~/builds/leviwilson
  - export ANDROID_HOME=~/builds/leviwilson/oasis-android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2 --no-ui --force
  - android update sdk --filter 6,10,33,41 --no-ui --force
  - android list targets
  - android update project -t 2 -p ./app
  - android update project -t 2 -p ./integration
  - echo no | android create avd -n android-10 -t 2
  - emulator-arm -avd android-10 -no-window -no-audio 1>&2 &
  - sh wait_for_emulator.sh
after_install:
  - killall emulator-arm
